name: solfeo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  auto_route: ^3.2.4
  soundpool: ^2.3.0
  material_design_icons_flutter: ^5.0.6595
  scrollable_positioned_list: ^0.2.3
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  offline_speech_recognition:
    path: offline_speech_recognition
  dio: ^4.0.6
  archive: ^3.3.0
  dartz: ^0.10.1
  lottie: ^1.2.2
  google_fonts: ^2.3.1
  flutter_signin_button: ^2.0.0
  animated_text_kit: ^4.2.1
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

  freezed: ^1.1.1
  json_serializable: ^6.1.5
  lint: ^1.8.2
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/sounds/
    - assets/animations/

  fonts:
    - family: BravuraText
      fonts:
        - asset: assets/fonts/BravuraText.otf
