// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6D7_OFyMJtQ9DS2Qi-wzvGfpRsoLYEaA',
    appId: '1:1046474183879:web:af2c0d95dde6bb48f39ae2',
    messagingSenderId: '1046474183879',
    projectId: 'solfa-f0d79',
    authDomain: 'solfa-f0d79.firebaseapp.com',
    storageBucket: 'solfa-f0d79.appspot.com',
    measurementId: 'G-Q4L07CBP9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7iqbqSfFruh0pz0JMMn1wJpLmcwrsdQ',
    appId: '1:1046474183879:android:9707ae715f6a97d1f39ae2',
    messagingSenderId: '1046474183879',
    projectId: 'solfa-f0d79',
    storageBucket: 'solfa-f0d79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5muiQoMshPV2GESCmNT-wJUizJyoHspQ',
    appId: '1:1046474183879:ios:53701a46a9e11693f39ae2',
    messagingSenderId: '1046474183879',
    projectId: 'solfa-f0d79',
    storageBucket: 'solfa-f0d79.appspot.com',
    iosClientId: '1046474183879-fea0a88cc443adqmtr6ohudvchju7bms.apps.googleusercontent.com',
    iosBundleId: 'ccv.checkhelzio.solfeo',
  );
}
